import { Roboto } from 'next/font/google'
import './globals.css';
import Header from './components/layout/Header';
import Footer from './components/layout/Footer';
import { Toaster } from 'react-hot-toast';
import { AppProvider } from '@/app/components/AppContext'

const roboto = Roboto({ subsets: ['latin'], weight: ['400', '500', '700'] })

export const metadata = {
  title: 'CarDiary App - krisii0327',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <main className='max-w-screen-2xl mx-auto'>
          <AppProvider>
              <Toaster />
              <Header />
              {children}
              <Footer />
          </AppProvider>
        </main>
      </body>
    </html>
  )
}
